name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: cleonissouza
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy artifact to GitHub Pages
        uses: actions/deploy-pages@v2
